In [1]:
import pandas as pd
import datetime
import numpy as np
import pickle
import sklearn
from sklearn.cross_validation import train_test_split 
from sklearn.ensemble import RandomForestRegressor
from sklearn import linear_model
from sklearn.metrics import *
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [9]:

col_list=['Page_popularity','Page_visited_no_of_times','Page_talking_about','Page_category','c1','c2','c3','c4','c5','c6','c7','c8',
         'c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19','c20','c21','c22','c23','c24','c25','CC1','CC2','CC3','CC4','CC5',
         'Base_time','Post_length_char_count','Post_share_count','Post_promoted','Time_target','Sunday_post','Monday_post',
         'Tuesday_post','Wednesday_post','Thrusday_post','Friday_post','Saturday_post','Sunday_base','Monday_base','Tuesday_base','Wednesday_base',
         'Thrusday_base','Friday_base','Saturday_base','Target_variable']

In [3]:
import logging 
import os
import zipfile
import boto.s3
import sys
from boto.s3.key import Key
import time
import datetime

accessKey='AKIAJICTHXTFCBM2PQMQ'
secretAccessKey='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'
inputLocation='USWest2'

if not accessKey or not secretAccessKey:
    logging.warning('Access Key and Secret Access Key not provided!!')
    print('Access Key and Secret Access Key not provided!!')
    exit()

AWS_ACCESS_KEY_ID = accessKey
AWS_SECRET_ACCESS_KEY = secretAccessKey

try:
    conn = boto.connect_s3(AWS_ACCESS_KEY_ID,
            AWS_SECRET_ACCESS_KEY)

    print("Connected to S3")

except:
    logging.info("Amazon keys are invalid!!")
    print("Amazon keys are invalid!!")
    exit()

Connected to S3

In [7]:
try:   
    bucket = conn.get_bucket('datadump101')
    print(bucket)
except:
    logging.info("Not connected to DataDump")
    print("Not connected to DataDump")
    exit()
    

url="https://s3-us-west-2.amazonaws.com/datadump101/Features_Variant_3.csv"

df =pd.read_csv(url)

<Bucket: datadump101>

In [8]:
df

,Page_popularity,Page_visited_no_of_times,Page_talking_about,Page_category,c1,c2,c3,c4,c5,c6,...,Friday_post,Saturday_post,Sunday_base,Monday_base,Tuesday_base,Wednesday_base,Thrusday_base,Friday_base,Saturday_base,Target_variable
0,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,0,0,1,0
1,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,0,0,1,0
2,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,1,0,0,0,0,0,0,0,1,0
3,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,1,0,1,0,0,0,0,0,0,0
4,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,1,0,0,0,0
5,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,1,0,0,0,0,0
6,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,1,0,0,0
7,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,1,0,0,0,0,0,0,0
8,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,1,0,0,0,0,0,0,1,0,0
9,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,1,0,0,1,0,0,0,0,0,0
10,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,1,0,0,0,0,0,0,1,0,0
11,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,1,0,0,0,0
12,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,0,1,0,0
13,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,0,1,0,0
14,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,1,0,0,0,0
15,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,1,0,0,0,0,3
16,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,1,0,0,2
17,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,0,0,1,0
18,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,1,0,0,0,0,0,0,0
19,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,1,0,0,0,0,0,0,0,1,0
20,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,1,0,0,0,0,0
21,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,1,0,0,0,5
22,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,1,0,0,0
23,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,1,0,0,0,0
24,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,0,1,0,0
25,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,1,0,0,0,0,0,0,0
26,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,1,0,0,0,0,0,0,0,1,0
27,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,1,0,0,0,0,2
28,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,1,0,0,0,0
29,634995,0,463,1,0,1280,14.807018,1.0,110.927036,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121068,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,2
121069,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,1,0,0,0,54
121070,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,1,0,0,0,85
121071,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,46
121072,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,0,1,0,38
121073,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,53
121074,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,1,0,1,0,0,0,0,0,0,4
121075,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,1,0,1,0,0,0,0,0,0,7
121076,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,1,1,0,0,0,0,0,0,10
121077,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,1,1,0,0,0,0,0,0,17
121078,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,1,0,1,0,0,0,0,0,6
121079,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,1,0,1,0,0,0,0,0,2
121080,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,1,0,0,0,0,0,74
121081,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,1,0,0,0,0,0,0,1816
121082,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,1,0,0,0,0,0,15
121083,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,1,0,0,0,0,3
121084,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,1,0,0,0,3
121085,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,1,0,0,0,0,0,373
121086,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,0
121087,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,0
121088,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,2
121089,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,1,0,0,0,0,19
121090,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,5
121091,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,1,0,0,0,78
121092,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,1,0,0,0,20
121093,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,12
121094,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,22
121095,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,45
121096,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,151
121097,7170111,70,497000,9,0,2113,456.581081,213.5,477.089459,0,...,0,0,0,0,0,0,1,0,0,193

In [10]:

df.columns=col_list
df_train,df_test = train_test_split(df,train_size=0.7,random_state=42)
column_list1=['CC2','Base_time','Post_share_count','c3','c8','c18','CC1','CC4','Post_length_char_count','CC5']
x_train=df_train[column_list1]
y_train=df_train['Target_variable']
scaler.fit(x_train)
x_train_sc=scaler.transform(x_train)
x_test=df_test[column_list1]
y_test=df_test['Target_variable']
scaler.fit(x_test)
x_test_sc=scaler.transform(x_test)
print(x_train.shape,',',x_test.shape,',',y_train.shape,',',y_test.shape)

(84768, 10) , (36330, 10) , (84768,) , (36330,)

In [11]:

df_summ=pd.DataFrame(columns=['Models','Dataset','R-sq','RMSE','MAE'])

In [13]:


lm=linear_model.LinearRegression()
lm.fit(x_train_sc,y_train)
filename = 'Models/Linear_model.sav'
pickle.dump(lm, open(filename, 'wb'))

In [14]:

y_train_pred=lm.predict(x_train_sc)
r2=r2_score(y_train,y_train_pred)
mae=mean_absolute_error(y_train,y_train_pred)
rmse=np.sqrt(mean_squared_error(y_train,y_train_pred))
mod='Linear Regression'
dataset='Training'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_train,y_train_pred))
print("MAE  :",mean_absolute_error(y_train,y_train_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_train,y_train_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

Linear Regression  on  Training  dataset   :
R2   : 0.35477580520968366
MAE  : 7.689121833497223
RMSE : 26.364490504815464

In [15]:


y_test_pred=lm.predict(x_test_sc)
r2=r2_score(y_test,y_test_pred)
mae=mean_absolute_error(y_test,y_test_pred)
rmse=np.sqrt(mean_squared_error(y_test,y_test_pred))
mod='Linear Regression'
dataset='Testing'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_test,y_test_pred))
print("MAE  :",mean_absolute_error(y_test,y_test_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_test,y_test_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

Linear Regression  on  Testing  dataset   :
R2   : 0.3337255693443989
MAE  : 7.733422155636673
RMSE : 28.5124327305569

In [16]:

rf=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=10,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=12, n_jobs=1,
           oob_score=False, random_state=42, verbose=0, warm_start=False)
rf.fit(x_train_sc, y_train)
filename = 'Models/RF_model.sav'
pickle.dump(rf, open(filename, 'wb'))

In [17]:

y_train_pred=rf.predict(x_train_sc)
r2=r2_score(y_train,y_train_pred)
mae=mean_absolute_error(y_train,y_train_pred)
rmse=np.sqrt(mean_squared_error(y_train,y_train_pred))
mod='Random Forest'
dataset='Training'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_train,y_train_pred))
print("MAE  :",mean_absolute_error(y_train,y_train_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_train,y_train_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

Random Forest  on  Training  dataset   :
R2   : 0.8817854950287961
MAE  : 3.0213794110086423
RMSE : 11.28494494854821

In [18]:

y_test_pred=rf.predict(x_test_sc)
r2=r2_score(y_test,y_test_pred)
mae=mean_absolute_error(y_test,y_test_pred)
rmse=np.sqrt(mean_squared_error(y_test,y_test_pred))
mod='Random Forest'
dataset='Testing'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_test,y_test_pred))
print("MAE  :",mean_absolute_error(y_test,y_test_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_test,y_test_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

Random Forest  on  Testing  dataset   :
R2   : 0.6664664015233934
MAE  : 4.100186394751551
RMSE : 20.17332544301502

In [19]:


mlp = MLPRegressor(activation='relu', alpha=1e-06, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15, 15, 15), learning_rate='constant',
       learning_rate_init=0.001, max_iter=50, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=42, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
mlp.fit(x_train_sc,y_train)
filename = 'Models/NN_model.sav'
pickle.dump(mlp, open(filename, 'wb'))

In [20]:

y_train_pred=mlp.predict(x_train_sc)
r2=r2_score(y_train,y_train_pred)
mae=mean_absolute_error(y_train,y_train_pred)
rmse=np.sqrt(mean_squared_error(y_train,y_train_pred))
mod='Neural Network'
dataset='Training'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_train,y_train_pred))
print("MAE  :",mean_absolute_error(y_train,y_train_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_train,y_train_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

Neural Network  on  Training  dataset   :
R2   : 0.684244402781427
MAE  : 4.04548324215259
RMSE : 18.443340732244252

In [21]:

y_test_pred=mlp.predict(x_test_sc)
r2=r2_score(y_test,y_test_pred)
mae=mean_absolute_error(y_test,y_test_pred)
rmse=np.sqrt(mean_squared_error(y_test,y_test_pred))
mod='Neural Network'
dataset='Testing'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_test,y_test_pred))
print("MAE  :",mean_absolute_error(y_test,y_test_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_test,y_test_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

Neural Network  on  Testing  dataset   :
R2   : 0.6513370439980815
MAE  : 4.196804734150779
RMSE : 20.625790591303247

In [22]:

knn = KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=2, p=2,
          weights='uniform')
knn.fit(x_train_sc,y_train)
filename = 'Models/KNN_model.sav'
pickle.dump(knn, open(filename, 'wb'))

In [23]:

y_train_pred=knn.predict(x_train_sc)
r2=r2_score(y_train,y_train_pred)
mae=mean_absolute_error(y_train,y_train_pred)
rmse=np.sqrt(mean_squared_error(y_train,y_train_pred))
mod='KNN'
dataset='Training'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_train,y_train_pred))
print("MAE  :",mean_absolute_error(y_train,y_train_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_train,y_train_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

KNN  on  Training  dataset   :
R2   : 0.8261136285009647
MAE  : 2.4944377595318987
RMSE : 13.686639660807698

In [24]:


y_test_pred=knn.predict(x_test_sc)
r2=r2_score(y_test,y_test_pred)
mae=mean_absolute_error(y_test,y_test_pred)
rmse=np.sqrt(mean_squared_error(y_test,y_test_pred))
mod='KNN'
dataset='Testing'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_test,y_test_pred))
print("MAE  :",mean_absolute_error(y_test,y_test_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_test,y_test_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

KNN  on  Testing  dataset   :
R2   : 0.4809799613884833
MAE  : 4.721758876961189
RMSE : 25.165163886570063

In [25]:


df_summ

              Models   Dataset      R-sq       RMSE       MAE
0  Linear Regression  Training  0.354776  26.364491  7.689122
1  Linear Regression   Testing  0.333726  28.512433  7.733422
2      Random Forest  Training  0.881785  11.284945  3.021379
3      Random Forest   Testing  0.666466  20.173325  4.100186
4     Neural Network  Training  0.684244  18.443341  4.045483
5     Neural Network   Testing  0.651337  20.625791  4.196805
6                KNN  Training  0.826114  13.686640  2.494438
7                KNN   Testing  0.480980  25.165164  4.721759

In [26]:


svr = SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)
svr.fit(x_train_sc,y_train)
filename = 'Models/SVR_model.sav'
pickle.dump(svr, open(filename, 'wb'))

In [ ]:

y_train_pred=svr.predict(x_train_sc)
r2=r2_score(y_train,y_train_pred)
mae=mean_absolute_error(y_train,y_train_pred)
rmse=np.sqrt(mean_squared_error(y_train,y_train_pred))
mod='SVR'
dataset='Training'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_train,y_train_pred))
print("MAE  :",mean_absolute_error(y_train,y_train_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_train,y_train_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

In [ ]:

y_test_pred=svr.predict(x_test_sc)
r2=r2_score(y_test,y_test_pred)
mae=mean_absolute_error(y_test,y_test_pred)
rmse=np.sqrt(mean_squared_error(y_test,y_test_pred))
mod='SVR'
dataset='Testing'
print(mod,' on ',dataset,' dataset ',' : ')
print("R2   :",r2_score(y_test,y_test_pred))
print("MAE  :",mean_absolute_error(y_test,y_test_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_test,y_test_pred)))
data={'Models':mod,'Dataset':dataset,'R-sq':r2,'RMSE':rmse,'MAE':mae}
df_summ=df_summ.append(data,ignore_index=True)

In [ ]:
df_summ

In [ ]:
df_summ.to_csv('Models/Summarry.csv',sep=',',index=False)

In [27]:
import shutil
shutil.make_archive("Models",'zip',"Models")

'C:\\Users\\Jerin\\Documents\\ADS\\Assignments\\Assignment2\\Models.zip'

Code to upload Model.zip to S3

In [5]:
try:   
    bucket = conn.get_bucket('adspickle1')
    print(bucket)
    bucket.set_acl('public-read')
except:
    logging.info("Amazon keys are invalid!!")
    print("Amazon keys are invalid!")
    exit()


def percent_cb(complete, total):
    sys.stdout.write('.')
    sys.stdout.flush()

zipfile = 'Models.zip'
k = Key(bucket)
k.key = 'Models'
k.set_contents_from_filename(zipfile,cb=percent_cb, num_cb=10)
print("Zip File successfully uploaded to S3")

<Bucket: adspickle1>
..........Zip File successfully uploaded to S3

Code to Download Models.zip from S3

In [2]:
bucket1 = conn.get_bucket('adspickle1')
srcFileName = 'Models'
k = Key(bucket1,srcFileName)
#Get the contents of the key into a file 
k.get_contents_to_filename('Models.zip')